//---------------------------------------------------------------------------

#ifndef InspectionFormH
#define InspectionFormH
//---------------------------------------------------------------------------
#include <Classes.hpp>
#include <Controls.hpp>
#include <StdCtrls.hpp>
#include <Forms.hpp>
#include "LMDControl.hpp"
#include "LMDCustomBevelPanel.hpp"
#include "LMDCustomControl.hpp"
#include "LMDCustomPanel.hpp"
#include "LMDCustomPanelFill.hpp"
#include "LMDCustomParentPanel.hpp"
#include "LMDCustomSheetControl.hpp"
#include "LMDPageControl.hpp"
#include "LMDCustomTrackBar.hpp"
#include "LMDTrackBar.hpp"
#include <ExtCtrls.hpp>
#include <Grids.hpp>
#include <ComCtrls.hpp>
#include <Graphics.hpp>
#include <Buttons.hpp>
#include "LMDButton.hpp"
#include "LMDCustomButton.hpp"
#include "LMDButtonControl.hpp"
#include "LMDCheckBox.hpp"
#include "LMDCustomCheckBox.hpp"
#include "LMDPNGImage.hpp"
#include "LMDCustomButtonGroup.hpp"
#include "LMDCustomGroupBox.hpp"
#include "LMDCustomRadioGroup.hpp"
#include "LMDRadioGroup.hpp"
#include <Dialogs.hpp>
#include <ExtDlgs.hpp>
#include <Menus.hpp>
#include "LMDBaseEdit.hpp"
#include "LMDCustomEdit.hpp"
#include "LMDEdit.hpp"
#include "LMDBaseControl.hpp"
#include "LMDBaseGraphicControl.hpp"
#include "LMDBaseMeter.hpp"
#include "LMDCustomProgress.hpp"
#include "LMDGraphicControl.hpp"
#include "LMDProgress.hpp"
//---------------------------------------------------------------------------
class TfrmInspection : public TForm
{
__published:	// IDE-managed Components
        TLMDPageControl *pcInspection;
        TLMDTabSheet *tsMacroInspection;
        TLMDTabSheet *tsMicroInspection;
        TLMDTabSheet *tsReferenceImage;
        TLMDTabSheet *tsRecipeInformation;
        TPanel *pnlMacroInspection;
        TGroupBox *gbDefectList;
        TStringGrid *sgDefectCount;
        TStringGrid *sgDefectDefine;
        TGroupBox *GroupBox2;
        TGroupBox *GroupBox3;
        TLabel *Label284;
        TLabel *Label283;
        TLMDTrackBar *tbLED2CH1;
        TPanel *pnlLED2CH1;
        TGroupBox *GroupBox4;
        TButton *Button1;
        TButton *Button2;
        TButton *Button3;
        TGroupBox *GroupBox5;
        TGroupBox *GroupBox6;
        TLabel *Label1;
        TLabel *Label2;
        TLMDTrackBar *LMDTrackBar1;
        TPanel *Panel1;
        TGroupBox *GroupBox7;
        TButton *Button4;
        TButton *Button5;
        TButton *Button6;
        TGroupBox *GroupBox8;
        TGroupBox *GroupBox9;
        TLabel *Label3;
        TLabel *Label4;
        TLMDTrackBar *LMDTrackBar2;
        TPanel *Panel2;
        TLabel *Label5;
        TLabel *Label6;
        TLabel *Label7;
        TLabel *Label8;
        TButton *Button11;
        TButton *btnMacroQuit;
        TButton *Button14;
        TButton *Button15;
        TButton *Button16;
        TPanel *pnlMicroInspection;
        TPanel *Panel3;
        TImage *imInspection;
        TGroupBox *GroupBox10;
        TGroupBox *GroupBox11;
        TGroupBox *GroupBox14;
        TGroupBox *GroupBox15;
        TGroupBox *GroupBox16;
        TGroupBox *rgAS;
        TButton *Button20;
        TButton *Button21;
        TButton *Button22;
        TButton *Button23;
        TButton *Button24;
        TButton *Button25;
        TButton *Button26;
        TTrackBar *TrackBar1;
        TButton *Button27;
        TPanel *Panel4;
        TPanel *pnlWafer;
        TLabel *Label9;
        TButton *Button34;
        TButton *btnDefaultIntensity;
        TButton *btnDec;
        TButton *btnAdd;
        TLabel *Label10;
        TLabel *Label25;
        TButton *btnGetAFPos;
        TLabel *Label27;
        TLabel *Label28;
        TPanel *pnlAFUnit01;
        TPanel *pnlAFUnit001;
        TLabel *Label29;
        TEdit *edAFMovUnit;
        TCheckBox *cbAF;
        TButton *btnDefaultAS;
        TLabel *Label30;
        TSpeedButton *btnAS1;
        TSpeedButton *btnAS2;
        TSpeedButton *btnAS3;
        TSpeedButton *btnAS4;
        TSpeedButton *btnAS5;
        TSpeedButton *btnAS6;
        TImage *Image2;
        TImage *Image3;
        TComboBox *ComboBox1;
        TGroupBox *GroupBox18;
        TTrackBar *TrackBar4;
        TSpeedButton *SpeedButton1;
        TPanel *Panel8;
        TPanel *Panel9;
        TPanel *Panel10;
        TPanel *Panel11;
        TPanel *pnlWaferMapSrc;
        TSpeedButton *SpeedButton2;
        TSpeedButton *SpeedButton9;
        TSpeedButton *SpeedButton10;
        TSpeedButton *SpeedButton11;
        TGroupBox *GroupBox19;
        TButton *Button41;
        TButton *Button42;
        TButton *Button43;
        TButton *Button44;
        TButton *btnMicroJudgPass;
        TButton *btnToEdge;
        TButton *btnMicroJudgReject;
        TButton *btnNextPoint;
        TButton *btnPreviousPoint;
        TButton *Button49;
        TGroupBox *GroupBox20;
        TSpeedButton *btnMoveLeftUp;
        TSpeedButton *btnMoveLeft;
        TSpeedButton *btnMoveLeftDown;
        TSpeedButton *btnMoveUp;
        TSpeedButton *btnMoveSpeed;
        TSpeedButton *btnMoveDown;
        TSpeedButton *btnMoveRightUp;
        TSpeedButton *btnMoveRight;
        TSpeedButton *btnMoveRightDown;
        TImage *imWaferMapSrc;
        TGroupBox *GroupBox21;
        TSpeedButton *btnSaveDie;
        TSpeedButton *SpeedButton23;
        TSpeedButton *btnSaveMainCCD;
        TSpeedButton *SpeedButton28;
        TSpeedButton *btnQuit;
        TSpeedButton *btnDrawMap;
        TPanel *Panel17;
        TPanel *Panel16;
        TImage *imMatchPattern;
        TLabel *Label37;
        TEdit *Edit9;
        TLabel *Label38;
        TSpeedButton *SpeedButton24;
        TSpeedButton *SpeedButton31;
        TPanel *Panel18;
        TGroupBox *GroupBox22;
        TLabel *Label39;
        TLabel *Label40;
        TPanel *pnlPort;
        TPanel *pnlCassetteID;
        TGroupBox *GroupBox23;
        TPanel *Panel21;
        TPanel *Panel22;
        TPanel *Panel23;
        TPanel *Panel24;
        TPanel *Panel25;
        TPanel *Panel26;
        TPanel *Panel27;
        TPanel *Panel28;
        TPanel *Panel29;
        TPanel *Panel30;
        TPanel *Panel31;
        TPanel *Panel32;
        TPanel *Panel33;
        TPanel *Panel34;
        TPanel *Panel35;
        TPanel *Panel36;
        TPanel *Panel37;
        TPanel *Panel38;
        TPanel *Panel39;
        TPanel *Panel40;
        TPanel *Panel41;
        TPanel *Panel42;
        TPanel *Panel43;
        TPanel *Panel44;
        TPanel *Panel45;
        TLabel *Label41;
        TLabel *Label42;
        TLabel *Label43;
        TLabel *Label44;
        TLabel *Label45;
        TLabel *Label46;
        TButton *Button30;
        TGroupBox *GroupBox24;
        TPanel *pnlAdminstrator;
        TPanel *pnlOperator;
        TGroupBox *GroupBox25;
        TPanel *pnlRemote;
        TPanel *pnlLineStatus;
        TPanel *pnlLocal;
        TGroupBox *GroupBox26;
        TGroupBox *GroupBox27;
        TPanel *Panel207;
        TPanel *Panel208;
        TPanel *Panel209;
        TPanel *Panel210;
        TGroupBox *GroupBox28;
        TPanel *Panel211;
        TPanel *Panel212;
        TPanel *Panel213;
        TPanel *Panel214;
        TGroupBox *GroupBox29;
        TGroupBox *GroupBox30;
        TPanel *Panel215;
        TPanel *Panel217;
        TPanel *Panel218;
        TGroupBox *GroupBox31;
        TPanel *Panel216;
        TPanel *Panel219;
        TPanel *Panel220;
        TGroupBox *GroupBox32;
        TPanel *Panel221;
        TPanel *Panel222;
        TGroupBox *GroupBox33;
        TPanel *Panel223;
        TPanel *Panel224;
        TGroupBox *GroupBox34;
        TPanel *Panel225;
        TPanel *Panel226;
        TLabel *Label72;
        TLabel *Label73;
        TRadioGroup *rgWaferDieDirection;
        TTimer *tm250ms;
        TShape *shMeasurePoint;
        TEdit *edLoopTestCount;
        TPanel *pnlLoopTestCount;
        TGroupBox *gbDIC;
        TButton *btnDICNear;
        TButton *btnDICFar;
        TLabel *Label47;
        TLabel *Label48;
        TLabel *Label49;
        TLabel *Label50;
        TLabel *Label51;
        TLabel *Label52;
        TLabel *Label53;
        TLabel *Label54;
        TLabel *Label55;
        TLabel *Label56;
        TLabel *Label57;
        TLabel *Label58;
        TLabel *Label59;
        TLabel *Label60;
        TLabel *Label61;
        TLabel *Label62;
        TLabel *Label63;
        TLabel *Label64;
        TLabel *Label65;
        TLabel *Label66;
        TLabel *Label67;
        TLabel *Label68;
        TLabel *Label69;
        TLabel *Label70;
        TLabel *Label71;
        TPanel *pnlWaferID25;
        TPanel *pnlWaferTop25;
        TPanel *pnlWaferBackEdge25;
        TPanel *pnlWaferBackCenter25;
        TPanel *pnlWaferMicro25;
        TPanel *pnlWaferWaferID25;
        TPanel *pnlWaferID24;
        TPanel *pnlWaferTop24;
        TPanel *pnlWaferBackEdge24;
        TPanel *pnlWaferBackCenter24;
        TPanel *pnlWaferMicro24;
        TPanel *pnlWaferWaferID24;
        TPanel *pnlWaferID23;
        TPanel *pnlWaferTop23;
        TPanel *pnlWaferBackEdge23;
        TPanel *pnlWaferBackCenter23;
        TPanel *pnlWaferMicro23;
        TPanel *pnlWaferWaferID23;
        TPanel *pnlWaferID22;
        TPanel *pnlWaferTop22;
        TPanel *pnlWaferBackEdge22;
        TPanel *pnlWaferBackCenter22;
        TPanel *pnlWaferMicro22;
        TPanel *pnlWaferWaferID22;
        TPanel *pnlWaferID21;
        TPanel *pnlWaferTop21;
        TPanel *pnlWaferBackEdge21;
        TPanel *pnlWaferBackCenter21;
        TPanel *pnlWaferMicro21;
        TPanel *pnlWaferWaferID21;
        TPanel *pnlWaferID20;
        TPanel *pnlWaferTop20;
        TPanel *pnlWaferBackEdge20;
        TPanel *pnlWaferBackCenter20;
        TPanel *pnlWaferMicro20;
        TPanel *pnlWaferWaferID20;
        TPanel *pnlWaferID19;
        TPanel *pnlWaferTop19;
        TPanel *pnlWaferBackEdge19;
        TPanel *pnlWaferBackCenter19;
        TPanel *pnlWaferMicro19;
        TPanel *pnlWaferWaferID19;
        TPanel *pnlWaferID18;
        TPanel *pnlWaferTop18;
        TPanel *pnlWaferBackEdge18;
        TPanel *pnlWaferBackCenter18;
        TPanel *pnlWaferMicro18;
        TPanel *pnlWaferWaferID18;
        TPanel *pnlWaferID17;
        TPanel *pnlWaferTop17;
        TPanel *pnlWaferBackEdge17;
        TPanel *pnlWaferBackCenter17;
        TPanel *pnlWaferMicro17;
        TPanel *pnlWaferWaferID17;
        TPanel *pnlWaferID16;
        TPanel *pnlWaferTop16;
        TPanel *pnlWaferBackEdge16;
        TPanel *pnlWaferBackCenter16;
        TPanel *pnlWaferMicro16;
        TPanel *pnlWaferWaferID16;
        TPanel *pnlWaferID15;
        TPanel *pnlWaferTop15;
        TPanel *pnlWaferBackEdge15;
        TPanel *pnlWaferBackCenter15;
        TPanel *pnlWaferMicro15;
        TPanel *pnlWaferWaferID15;
        TPanel *pnlWaferID14;
        TPanel *pnlWaferTop14;
        TPanel *pnlWaferBackEdge14;
        TPanel *pnlWaferBackCenter14;
        TPanel *pnlWaferMicro14;
        TPanel *pnlWaferWaferID14;
        TPanel *pnlWaferID13;
        TPanel *pnlWaferTop13;
        TPanel *pnlWaferBackEdge13;
        TPanel *pnlWaferBackCenter13;
        TPanel *pnlWaferMicro13;
        TPanel *pnlWaferWaferID13;
        TPanel *pnlWaferID12;
        TPanel *pnlWaferTop12;
        TPanel *pnlWaferBackEdge12;
        TPanel *pnlWaferBackCenter12;
        TPanel *pnlWaferMicro12;
        TPanel *pnlWaferWaferID12;
        TPanel *pnlWaferID11;
        TPanel *pnlWaferTop11;
        TPanel *pnlWaferBackEdge11;
        TPanel *pnlWaferBackCenter11;
        TPanel *pnlWaferMicro11;
        TPanel *pnlWaferWaferID11;
        TPanel *pnlWaferID10;
        TPanel *pnlWaferTop10;
        TPanel *pnlWaferBackEdge10;
        TPanel *pnlWaferBackCenter10;
        TPanel *pnlWaferMicro10;
        TPanel *pnlWaferWaferID10;
        TPanel *pnlWaferID09;
        TPanel *pnlWaferTop09;
        TPanel *pnlWaferBackEdge09;
        TPanel *pnlWaferBackCenter09;
        TPanel *pnlWaferMicro09;
        TPanel *pnlWaferWaferID09;
        TPanel *pnlWaferID08;
        TPanel *pnlWaferTop08;
        TPanel *pnlWaferBackEdge08;
        TPanel *pnlWaferBackCenter08;
        TPanel *pnlWaferMicro08;
        TPanel *pnlWaferWaferID08;
        TPanel *pnlWaferID07;
        TPanel *pnlWaferTop07;
        TPanel *pnlWaferBackEdge07;
        TPanel *pnlWaferBackCenter07;
        TPanel *pnlWaferMicro07;
        TPanel *pnlWaferWaferID07;
        TPanel *pnlWaferID06;
        TPanel *pnlWaferTop06;
        TPanel *pnlWaferBackEdge06;
        TPanel *pnlWaferBackCenter06;
        TPanel *pnlWaferMicro06;
        TPanel *pnlWaferWaferID06;
        TPanel *pnlWaferID05;
        TPanel *pnlWaferTop05;
        TPanel *pnlWaferBackEdge05;
        TPanel *pnlWaferBackCenter05;
        TPanel *pnlWaferMicro05;
        TPanel *pnlWaferWaferID05;
        TPanel *pnlWaferID04;
        TPanel *pnlWaferTop04;
        TPanel *pnlWaferBackEdge04;
        TPanel *pnlWaferBackCenter04;
        TPanel *pnlWaferMicro04;
        TPanel *pnlWaferWaferID04;
        TPanel *pnlWaferID03;
        TPanel *pnlWaferTop03;
        TPanel *pnlWaferBackEdge03;
        TPanel *pnlWaferBackCenter03;
        TPanel *pnlWaferMicro03;
        TPanel *pnlWaferWaferID03;
        TPanel *pnlWaferID02;
        TPanel *pnlWaferTop02;
        TPanel *pnlWaferBackEdge02;
        TPanel *pnlWaferBackCenter02;
        TPanel *pnlWaferMicro02;
        TPanel *pnlWaferWaferID02;
        TPanel *pnlWaferID01;
        TPanel *pnlWaferTop01;
        TPanel *pnlWaferBackEdge01;
        TPanel *pnlWaferBackCenter01;
        TPanel *pnlWaferMicro01;
        TPanel *pnlWaferWaferID01;
        TPanel *pnlMacroJudge;
        TPanel *pnlMicroJudge;
        TPanel *Panel46;
        TGroupBox *gbMacroOperation;
        TLMDButton *btnMacroHome;
        TPanel *pnlMacroHome;
        TLMDButton *btnMacroRobotPosition;
        TPanel *pnlMacroRobotPosition;
        TLMDButton *btnMacroReadyPosition;
        TPanel *pnlMacroReadyPosition;
        TLMDButton *btnMacroInnerPosition;
        TPanel *pnlMacroInnerPosition;
        TLMDButton *btnMacroOuterPosition;
        TPanel *pnlMacroOuterPosition;
        TLMDButton *btnMacroInnerXMove;
        TPanel *pnlMacroInnerXMove;
        TLMDButton *btnMacroInnerYMove;
        TPanel *pnlMacroInnerYMove;
        TLMDButton *btnMacroOuterTCW;
        TPanel *pnlMacroOuterTCW;
        TLMDButton *btnMacroOuterTCCW;
        TPanel *pnlMacroOuterTCCW;
        TLMDButton *btnMacroInnerTMove;
        TPanel *pnlMacroInnerTMove;
        TLMDButton *btnMacroInnerYBack;
        TPanel *pnlMacroInnerYBack;
        TLMDButton *btnMacroInnerXBack;
        TPanel *pnlMacroInnerXBack;
        TLMDButton *btnMacroInnerTBack;
        TPanel *pnlMacroInnerTBack;
        TLMDButton *btnMacroInnerStop;
        TPanel *pnlMacroInnerStop;
        TLMDButton *btnMacroOuterStop;
        TPanel *pnlMacroOuterStop;
        TShape *shHorizontal;
        TShape *shVertical;
        TLMDRadioGroup *rgBXFMLens;
        TPanel *pnlBXFMLens;
        TLMDTrackBar *tbBXFMLMP;
        TPanel *pnlBXFMLMPValue;
        TPanel *pnlBXFMLampSet;
        TLabel *Label76;
        TPanel *pnlASValue;
        TLMDButton *btnMacroInverse;
        TPanel *pnlMacroInverse;
        TGroupBox *gbMacroResult;
        TLabel *Label77;
        TLabel *Label78;
        TPanel *pnlMacroTopResult;
        TPanel *pnlMacroBackResult;
        TLMDButton *btnMacroDone;
        TButton *btnMacroJudgPasse;
        TButton *btnMacroJudgReject;
        TPanel *pnlLeftCCD;
        TPanel *pnlRightCCD;
        TImage *imLeftCCD;
        TImage *imRightCCD;
        TLabel *laLeftCCD;
        TLabel *laRightCCD;
        TShape *shLeftHorizontal;
        TShape *shLeftVertical;
        TShape *shRightHorizontal;
        TShape *shRightVertical;
        TPanel *pnlLeftFactor;
        TPanel *pnlRightFactor;
        TLMDCheckBox *cbCCDFullImageLR;
        TCheckBox *cbFreezeRL;
        TButton *btnSaveLeftCCD;
        TButton *btnSaveRightCCD;
        TLMDRadioGroup *rgFileFormat;
        TSavePictureDialog *spCCDImage;
        TLMDRadioGroup *rgSpeed;
        TPanel *pnlWheelMsg;
        TRadioGroup *rgMeasurePoint;
        TLabel *Label450;
        TLabel *Label451;
        TPanel *pnlChipRow;
        TPanel *pnlChipCol;
        TPanel *pnlCenterCol;
        TPanel *pnlCenterRow;
        TPanel *pnlX;
        TPanel *pnlY;
        TLabel *Label26;
        TButton *Button38;
        TEdit *Edit1;
        TPanel *pnlLeftMacroLamp;
        TPanel *pnlRightMacroLamp;
        TLabel *Label81;
        TLabel *Label82;
        TPanel *pnlLeftCCDX;
        TPanel *pnlLeftCCDY;
        TPanel *pnlLeftCCDR;
        TPanel *pnlLeftCCDG;
        TPanel *pnlLeftCCDB;
        TLabel *Label83;
        TLabel *Label84;
        TPanel *pnlRightCCDX;
        TPanel *pnlRightCCDY;
        TPanel *pnlRightCCDR;
        TPanel *pnlRightCCDG;
        TPanel *pnlRightCCDB;
        TPanel *pnlLeftLight;
        TPanel *pnlRightLight;
        TLMDTabSheet *tsMeasurement;
        TPanel *Panel49;
        TPanel *pnlMeasureTool;
        TBitBtn *btnLine;
        TBitBtn *btnVLine;
        TBitBtn *btnAngle;
        TBitBtn *btnHorLine;
        TBitBtn *btnVerLine;
        TBitBtn *btnCircle;
        TLabel *Label31;
        TLabel *Label74;
        TLabel *Label75;
        TPanel *pnlCCDX;
        TPanel *pnlCCDY;
        TPanel *pnlCCDR;
        TPanel *pnlCCDG;
        TPanel *pnlCCDB;
        TLabel *Label93;
        TPanel *pnlMainFactor;
        TPanel *Panel7;
        TImage *imAdd;
        TPanel *Panel14;
        TImage *imDec;
        TRadioGroup *rgObservation;
        TRadioGroup *rgEdgeNo;
        TCheckBox *cbFreeze;
        TLMDCheckBox *cbCCDFullImage;
        TLabel *Label34;
        TEdit *edSelectCol;
        TEdit *edSelectRow;
        TButton *btnColRowTo;
        TGroupBox *GroupBox12;
        TLabel *Label13;
        TLabel *Label14;
        TLabel *Label11;
        TLabel *Label12;
        TLabel *Label15;
        TLabel *Label16;
        TLabel *Label17;
        TLabel *Label18;
        TLabel *Label19;
        TLabel *Label20;
        TLabel *Label21;
        TLabel *Label22;
        TLabel *Label23;
        TLabel *Label24;
        TGroupBox *gbDefectList1;
        TStringGrid *sgDefectList;
        TGroupBox *gbBincode;
        TStringGrid *sgBINCode;
        TPanel *pnlDie;
        TShape *Shape1;
        TShape *Shape2;
        TShape *Shape3;
        TShape *Shape4;
        TLMDButton *btnWaferMapDraw;
        TGroupBox *GroupBox36;
        TLMDButton *btnCW1x;
        TLMDButton *btnCCW1x;
        TPanel *Panel51;
        TButton *btnMicroDidJudgPass;
        TButton *btnMicroDidJudgReject;
        TGroupBox *gbMeasure;
        TStringGrid *sgMeasure;
        TPanel *Panel52;
        TImage *imMeasure;
        TShape *shMeasureHLine;
        TShape *shMeasureVLine;
        TPanel *pnlRatio;
        TLMDCheckBox *cbCCDFullImageMeasure;
        TLabel *Label94;
        TPanel *pnlMeasureX;
        TPanel *pnlMeasureY;
        TLabel *Label95;
        TPanel *pnlMeasureR;
        TPanel *pnlMeasureG;
        TPanel *pnlMeasureB;
        TRadioGroup *rgWaferDegree;
        TRadioGroup *rgCCDShutter;
        TCheckBox *cbWBAuto;
        TLMDButton *btnWBOneTouch;
        TPanel *pnlWorkCol;
        TPanel *pnlWorkRow;
        TRadioGroup *rgLeftCCDShutter;
        TLabel *Label85;
        TLabel *Label86;
        TLabel *Label87;
        TLabel *Label88;
        TLMDTrackBar *LMDTrackBar3;
        TPanel *Panel19;
        TRadioGroup *rgRightCCDShutter;
        TImage *imClose;
        TCheckBox *cbFreezeMeasure;
        TShape *shCurretnPosition;
        TRadioGroup *rgMoveStep;
        TRadioGroup *rgWaferType;
        TPanel *pnlSystemMessage;
        TSpeedButton *SpeedButton21;
        TPanel *pnlZ;
        TPanel *pnlT;
        TButton *btnAFUp;
        TButton *btnAFDown;
        TLabel *Label33;
        TLabel *Label35;
        TButton *btnMicroQuit;
        TPanel *pnlStageMoving;
        TTimer *tmUpdatePosition;
        TPanel *pnlCircle;
        TLabel *laMessage;
        TLabel *Label189;
        TLabel *Label190;
        TLabel *Label191;
        TLabel *Label192;
        TLabel *Label193;
        TLabel *laCircleCenter;
        TLabel *laCircleRadius;
        TLabel *laCircleArea;
        TLabel *laCircleRadiusUnit;
        TLabel *laCircleAreaUnit;
        TLabel *laAngle;
        TLabel *laAngleUnit;
        TPanel *Panel12;
        TLMDButton *btnCircleCompute;
        TPanel *pnlCircleP1X;
        TPanel *pnlCircleP1Y;
        TPanel *pnlCircleP2X;
        TPanel *pnlCircleP2Y;
        TPanel *pnlCircleP3X;
        TPanel *pnlCircleP3Y;
        TPanel *pnlCircleCenterX;
        TPanel *pnlCircleRadius;
        TPanel *pnlCircleArea;
        TLMDButton *btnCircleP1Set;
        TLMDButton *btnCircleP2Set;
        TLMDButton *btnCircleP3Set;
        TPanel *pnlCircleP1Status;
        TPanel *pnlCircleP2Status;
        TPanel *pnlCircleP3Status;
        TLMDButton *btnCircleExit;
        TPanel *pnlCircleCenterY;
        TPanel *pnlAngle;
        TPanel *pnlAngle12;
        TLMDButton *btnClear;
        TLMDRadioGroup *rgCircleNo;
        TPopupMenu *pmPointSet;
        TMenuItem *mnPoint1;
        TMenuItem *mnPoint2;
        TMenuItem *mnPoint3;
        TMenuItem *mnRecord;
        TMenuItem *mnLineLength1;
        TMenuItem *mnLineLength2;
        TMenuItem *mnCirclePoint1;
        TMenuItem *mnCirclePoint2;
        TMenuItem *mnSetPoint;
        TShape *shPoint1;
        TPanel *pnlPoint1;
        TPanel *pnlPoint2;
        TShape *shPoint2;
        TShape *shPoint3;
        TPanel *pnlPoint3;
        TShape *shCircleCenter1;
        TPanel *pnlCircleCenter1;
        TShape *shCircleCenter2;
        TPanel *pnlCircleCenter2;
        TShape *shCirclePoint1;
        TPanel *pnlCirclePoint1;
        TShape *shCirclePoint2;
        TPanel *pnlCirclePoint2;
        TLMDCheckBox *cbPointSetDisplay;
        TPanel *pnlPointSet1;
        TShape *shPointSet1;
        TShape *shPointSet2;
        TPanel *pnlPointSet2;
        TShape *shPointSet3;
        TPanel *pnlPointSet3;
        TShape *shPointSet4;
        TPanel *pnlPointSet4;
        TShape *shPointSet5;
        TPanel *pnlPointSet5;
        TShape *shLineSet2;
        TPanel *pnlLineSet2;
        TShape *shLineSet1;
        TPanel *pnlLineSet1;
        TMemo *mmMeasure;
        TShape *shCircle;
        TShape *shCircleMark1;
        TShape *shCircleMark2;
        TPanel *pnlUnit;
        TImage *imDraw;
        TLMDButton *btnLoadTestImage;
        TLMDButton *btnClearDraw;
        TPanel *pnlData;
        TPanel *pnlToolSelect;
        TPopupMenu *pmMeasureData;
        TMenuItem *mnDeleteItem;
        TMenuItem *mnDisplayItem;
        TPanel *pnlPrecision;
        TLabel *Label36;
        TLabel *Label79;
        TPanel *pnlCircleP4X;
        TPanel *pnlCircleP4Y;
        TMenuItem *mnSave;
        TSaveDialog *sdMeasureData;
        TColorDialog *cdMeasureData;
        TLMDButton *btnLineColor;
        TPanel *pnlLineColor;
        TLMDButton *btnTextColor;
        TPanel *pnlTextColor;
        TLMDButton *btnFontColor;
        TPanel *pnlFontColor;
        TPanel *pnlLensPrecision;
        TCheckBox *cbAutoExposure;
        TPanel *pnlLoadingNextWafer;
        TCheckBox *cbMeasureCrossLine;
        TCheckBox *cbMicroCrossLine;
        TCheckBox *cbMacroTopCrossLine;
        TCheckBox *cbMacroBackCrossLine;
        TPanel *pnlDICNear;
        TPanel *pnlDICFar;
        TMenuItem *mnDeleteAll;
        TBitBtn *btnHeight;
        TPanel *pnlXFactor;
        TPanel *pnlYFactor;
        TSpeedButton *btnMoveUpMeasure;
        TSpeedButton *btnMoveDownMeasure;
        TPanel *pnlZValue1;
        TRadioGroup *rgMoveStepMeasure;
        TPanel *pnlZValue2;
        TPanel *pnlZMeasure;
        TLMDTrackBar *tbDICFC;
        TPanel *pnlDICBar;
        TPanel *pnlObservation;
        TPanel *pnlAFPos;
        TLMDButton *btnTOrg;
        TGroupBox *gbWaferIDParameters;
        TRadioGroup *rgWaferIDDegree1;
        TCheckBox *cbReadWaferID1;
        TGroupBox *gbMacroParameters;
        TLabel *Label80;
        TLabel *Label89;
        TLabel *Label90;
        TLabel *Label91;
        TLabel *Label92;
        TLabel *Label96;
        TLabel *Label97;
        TLabel *Label98;
        TLabel *Label99;
        TLabel *Label100;
        TLabel *Label101;
        TLabel *Label102;
        TLabel *Label103;
        TLabel *Label104;
        TLabel *Label105;
        TLabel *Label106;
        TLabel *Label107;
        TLabel *Label108;
        TLabel *Label109;
        TLabel *Label110;
        TLabel *Label111;
        TLabel *Label112;
        TRadioGroup *rgMacroTopLoadPosition;
        TEdit *edMacroTopHomeDuration;
        TEdit *edMacroTopLeftDuration;
        TEdit *edMacroTopRightDuration;
        TEdit *edMacroTopViewDuration;
        TLMDButton *btnMacroTopTo;
        TPanel *pnlMacroTopTo;
        TRadioGroup *rgMacroBackLoadPosition;
        TEdit *edMacroBackHomeDuration;
        TEdit *edMacroBackLeftDuration;
        TEdit *edMacroBackRightDuration;
        TEdit *edMacroBackViewDuration;
        TLMDButton *btnMacroBackTo;
        TPanel *pnlMacroBackTo;
        TCheckBox *cbAutoSaveMacro;
        TPanel *pnlTopMacroLeftLamp;
        TPanel *pnlTopMacroRightLamp;
        TPanel *pnlBackMacroLeftLamp;
        TPanel *pnlBackMacroRightLamp;
        TPanel *Panel13;
        TEdit *edLotID;
        TPanel *Panel20;
        TEdit *edSlotNo;
        TSpeedButton *btnAS0;
        TLabel *Label115;
        TRadioGroup *rgWaferIDDegree2;
        TCheckBox *cbReadWaferID2;
        TGroupBox *GroupBox13;
        TLabel *Label443;
        TLabel *Label444;
        TLabel *Label445;
        TLabel *Label446;
        TLabel *Label447;
        TLabel *Label452;
        TLabel *Label453;
        TLabel *Label454;
        TLabel *Label455;
        TLabel *Label605;
        TLabel *Label604;
        TLabel *Label32;
        TLabel *Label448;
        TLabel *Label449;
        TEdit *edChipWidth;
        TEdit *edChipHeight;
        TEdit *edChipDx;
        TEdit *edChipDy;
        TEdit *edIgnore;
        TEdit *Edit4;
        TScrollBar *ScrollBar2;
        TEdit *Edit5;
        TScrollBar *ScrollBar3;
        TEdit *Edit6;
        TScrollBar *ScrollBar4;
        TPanel *pnlChipHNo;
        TPanel *pnlChipWNo;
        TLabel *Label116;
        TEdit *edSubDieXno;
        TEdit *edSubDieYno;
        TLabel *Label117;
        TStringGrid *sgDie;
        TLMDButton *btnBackwardZ1;
        TLMDButton *btnMoveZ1;
        TButton *btnFindCenter;
        TCheckBox *CheckBox2;
        TLMDButton *btnAlignment;
        TPanel *pnlAlignment;
        TLMDButton *btnAutoMatch;
        TPanel *pnlAutoMatch;
        TShape *shMarkMatch;
        TShape *shCenter;
        TPanel *pnlPattern;
        TImage *imPattern;
        TTimer *tmFindCenter;
        TPanel *pnlCenterX;
        TPanel *pnlCenterY;
        TEdit *edSubDieWidth;
        TEdit *edSubDieHeight;
        TPanel *pnlAutoSaveMessage;
        TGroupBox *GroupBox35;
        TLabel *laImgTest;
        TLabel *Label206;
        TLMDEdit *edMinScore;
        TComboBox *cbMatchNo;
        TLMDRadioGroup *rgMatchSource;
        TCheckBox *cbMoveToCenterMatched;
        TCheckBox *cbStdPattern;
        TLMDCheckBox *cbDirectMoveDirection;
        TLMDCheckBox *cbDirectMove;
        TLMDCheckBox *cbRotateDirection;
        TPanel *pnlRemoteRotate;
        TPanel *pnlTRemoteOffset;
        TPanel *pnlDegree;
        TPanel *pnlTRemoteDegree;
        TPanel *pnlScore;
        TPanel *pnlMatchedNo;
        TLabel *Label113;
        TLabel *Label114;
        TLabel *Label118;
        TLabel *Label119;
        TLabel *Label120;
        TLabel *Label121;
        TPanel *pnlBase1X;
        TPanel *pnlBase1Y;
        TPanel *pnlBase2X;
        TPanel *pnlBase2Y;
        TPanel *pnlPositionX;
        TPanel *pnlPositionY;
        TPanel *pnlStdZ;
        TPanel *pnlStdT;
        TCheckBox *cbAutoSaveMicro;
        TPopupMenu *pmDieJudge;
        TMenuItem *mnDefectPass;
        TMenuItem *mnDefectReject;
        TGroupBox *GroupBox37;
        TCheckBox *cbGlassIQCF;
        TCheckBox *cbGlassIQCB;
        TCheckBox *cbGlassOQCF;
        TCheckBox *cbGlassOQCB;
        TCheckBox *cbSiIQCSS;
        TCheckBox *cbSiIQCLS;
        TCheckBox *cbSiIQCPad;
        TCheckBox *cbSiIQCSA;
        TCheckBox *cbSiOQCSS;
        TCheckBox *cbSiOQCLS;
        TCheckBox *cbSiOQCPad;
        TCheckBox *cbSiOQCW;
        TPanel *pnlTxtNumber;
        TPanel *pnlItemNumber;
        TCheckBox *cbGood;
        TCheckBox *cbNA;
        TPanel *pnlAutoSaveMicro;
        TPanel *pnlMicroResult;
        TShape *Shape5;
        TShape *Shape6;
        TStringGrid *sgBINCodeResult;
        TPanel *pnlResultTitle;
        TLabel *Label122;
        TLabel *Label123;
        TLabel *Label125;
        TLabel *Label126;
        TLabel *Label127;
        TLabel *Label128;
        TLabel *Label129;
        TLabel *Label130;
        TLabel *Label131;
        TLabel *Label132;
        TLabel *Label133;
        TPanel *pnlWaferMapResult;
        TImage *imWaferMapResult;
        TLabel *laTestedDateTime;
        TLabel *laDiameter;
        TLabel *laGross;
        TLabel *laDegree;
        TGroupBox *GroupBox17;
        TRadioGroup *rgWaferInLP1Degree;
        TRadioGroup *rgWaferOutLP1Degree;
        TRadioGroup *rgWaferInLP2Degree;
        TRadioGroup *rgWaferOutLP2Degree;
        TLabel *laRecipeID;
        TLabel *laWidth;
        TLabel *laHeight;
        TLabel *laFilename;
        TLabel *laLens;
        TMenuItem *mnDefectNone;
        TRadioGroup *rgImageSaveMode;
        TPopupMenu *pmMap;
        TMenuItem *mnAddPoint;
        TPopupMenu *pmPoint;
        TMenuItem *mnDeletePoint;
        TLabel *Label124;
        TEdit *edMinYield;
        TLabel *Label134;
        TLabel *laMinYield;
        TMenuItem *mnRestorePoint;
        TPanel *pnlAF;
        TRadioGroup *rgWaferAxisOrientation;
        TLabel *Label135;
        TEdit *edPatternIntensity;
        TLMDRadioGroup *rgPatternLens;
        TLabel *Label136;
        TLabel *laTestedNo;
        TPanel *pnlMacroJudageDone;
        TPanel *pnlMicroJudageDone;
        TLabel *Label137;
        TPanel *pnlCenterDefineX;
        TPanel *pnlCenterDefineY;
        TEdit *edPositionIntensity;
        TPopupMenu *pmMapSubDie;
        TMenuItem *mnAddSubDie;
        TButton *btnStopSave;
        TCheckBox *cbDieInsideAll;
        TGroupBox *GroupBox1;
        TLabel *Label138;
        TLabel *Label139;
        TEdit *edDieSaveOverlap;
        TLMDProgress *pbDieSave;
        void __fastcall FormShow(TObject *Sender);
        void __fastcall sgDefectCountDrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
        void __fastcall sgDefectDefineDrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
        void __fastcall btnWaferMapDrawClick(TObject *Sender);
        void __fastcall imWaferMapSrcMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall imWaferMapSrcMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
        void __fastcall tm250msTimer(TObject *Sender);
        void __fastcall rgMeasurePointClick(TObject *Sender);
        void __fastcall FormClose(TObject *Sender, TCloseAction &Action);
        void __fastcall imInspectionMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall imInspectionMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
        void __fastcall imInspectionMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall FormMouseWheelDown(TObject *Sender,
          TShiftState Shift, TPoint &MousePos, bool &Handled);
        void __fastcall imAddClick(TObject *Sender);
        void __fastcall imDecClick(TObject *Sender);
        void __fastcall FormMouseWheelUp(TObject *Sender,
          TShiftState Shift, TPoint &MousePos, bool &Handled);
        void __fastcall btnMacroJudgPasseClick(TObject *Sender);
        void __fastcall btnMacroJudgRejectClick(TObject *Sender);
        void __fastcall btnMicroJudgPassClick(TObject *Sender);
        void __fastcall btnMicroJudgRejectClick(TObject *Sender);
        void __fastcall btnMacroHomeClick(TObject *Sender);
        void __fastcall btnMacroInnerPositionClick(TObject *Sender);
        void __fastcall btnMacroInnerStopClick(TObject *Sender);
        void __fastcall btnMacroOuterPositionClick(TObject *Sender);
        void __fastcall btnMacroOuterStopClick(TObject *Sender);
        void __fastcall btnMacroRobotPositionClick(TObject *Sender);
        void __fastcall btnMacroReadyPositionClick(TObject *Sender);
        void __fastcall btnMacroInnerYMoveMouseExit(TObject *Sender);
        void __fastcall btnMacroInnerYMoveMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerXBackMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerXBackMouseExit(TObject *Sender);
        void __fastcall btnMacroInnerXBackMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerTMoveMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerTMoveMouseExit(TObject *Sender);
        void __fastcall btnMacroInnerTMoveMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroOuterTCCWMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroOuterTCCWMouseExit(TObject *Sender);
        void __fastcall btnMacroOuterTCCWMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerYBackMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerYBackMouseExit(TObject *Sender);
        void __fastcall btnMacroInnerYBackMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerXMoveMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerXMoveMouseExit(TObject *Sender);
        void __fastcall btnMacroInnerXMoveMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerTBackMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerTBackMouseExit(TObject *Sender);
        void __fastcall btnMacroInnerTBackMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroOuterTCWMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroOuterTCWMouseExit(TObject *Sender);
        void __fastcall btnMacroOuterTCWMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMacroInnerYMoveMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall rgBXFMLensChange(TObject *Sender, int ButtonIndex);
        void __fastcall tbBXFMLMPMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnDecClick(TObject *Sender);
        void __fastcall btnAddClick(TObject *Sender);
        void __fastcall btnDefaultIntensityClick(TObject *Sender);
        void __fastcall btnDefaultASClick(TObject *Sender);
        void __fastcall btnAS1Click(TObject *Sender);
        void __fastcall btnAS2Click(TObject *Sender);
        void __fastcall btnAS3Click(TObject *Sender);
        void __fastcall btnAS4Click(TObject *Sender);
        void __fastcall btnAS5Click(TObject *Sender);
        void __fastcall btnAS6Click(TObject *Sender);
        void __fastcall btnMacroInverseClick(TObject *Sender);
        void __fastcall btnMacroDoneClick(TObject *Sender);
        void __fastcall imLeftCCDMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall imLeftCCDMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
        void __fastcall imLeftCCDMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall imRightCCDMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall imRightCCDMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
        void __fastcall imRightCCDMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnSaveLeftCCDClick(TObject *Sender);
        void __fastcall btnSaveRightCCDClick(TObject *Sender);
        void __fastcall btnMoveLeftClick(TObject *Sender);
        void __fastcall btnMoveRightClick(TObject *Sender);
        void __fastcall btnMoveUpClick(TObject *Sender);
        void __fastcall btnMoveDownClick(TObject *Sender);
        void __fastcall btnMoveSpeedClick(TObject *Sender);
        void __fastcall btnSaveMainCCDClick(TObject *Sender);
        void __fastcall btnMoveLeftUpClick(TObject *Sender);
        void __fastcall btnMoveLeftDownClick(TObject *Sender);
        void __fastcall btnMoveRightUpClick(TObject *Sender);
        void __fastcall btnMoveRightDownClick(TObject *Sender);
        void __fastcall sgBINCodeDrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
        void __fastcall sgDefectListDrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
        void __fastcall cbWBAutoClick(TObject *Sender);
        void __fastcall btnWBOneTouchClick(TObject *Sender);
        void __fastcall rgObservationClick(TObject *Sender);
        void __fastcall btnNextPointClick(TObject *Sender);
        void __fastcall btnPreviousPointClick(TObject *Sender);
        void __fastcall sgDefectListDblClick(TObject *Sender);
        void __fastcall rgCCDShutterClick(TObject *Sender);
        void __fastcall rgLeftCCDShutterClick(TObject *Sender);
        void __fastcall rgRightCCDShutterClick(TObject *Sender);
        void __fastcall sgDefectListClick(TObject *Sender);
        void __fastcall btnCW1xClick(TObject *Sender);
        void __fastcall btnCCW1xClick(TObject *Sender);
        void __fastcall FormMouseMove(TObject *Sender, TShiftState Shift,
          int X, int Y);
        void __fastcall imCloseClick(TObject *Sender);
        void __fastcall rgMoveStepClick(TObject *Sender);
        void __fastcall imWaferMapSrcDblClick(TObject *Sender);
        void __fastcall btnColRowToClick(TObject *Sender);
        void __fastcall cbAFClick(TObject *Sender);
        void __fastcall pnlAFUnit01Click(TObject *Sender);
        void __fastcall pnlAFUnit001Click(TObject *Sender);
        void __fastcall btnGetAFPosClick(TObject *Sender);
        void __fastcall btnAFUpClick(TObject *Sender);
        void __fastcall btnAFDownClick(TObject *Sender);
        void __fastcall btnMacroQuitClick(TObject *Sender);
        void __fastcall btnMicroQuitClick(TObject *Sender);
        void __fastcall tmUpdatePositionTimer(TObject *Sender);
        void __fastcall mnPoint1Click(TObject *Sender);
        void __fastcall imMeasureDblClick(TObject *Sender);
        void __fastcall cbPointSetDisplayChange(TObject *Sender);
        void __fastcall btnCircleClick(TObject *Sender);
        void __fastcall btnAngleClick(TObject *Sender);
        void __fastcall mnPoint2Click(TObject *Sender);
        void __fastcall mnPoint3Click(TObject *Sender);
        void __fastcall btnCircleComputeClick(TObject *Sender);
        void __fastcall shCircleMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
        void __fastcall btnCircleExitClick(TObject *Sender);
        void __fastcall imMeasureMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall imMeasureMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
        void __fastcall imMeasureMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnLineClick(TObject *Sender);
        void __fastcall btnVLineClick(TObject *Sender);
        void __fastcall btnClearDrawClick(TObject *Sender);
        void __fastcall btnLoadTestImageClick(TObject *Sender);
        void __fastcall sgMeasureDrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
        void __fastcall cbCCDFullImageMeasureClick(TObject *Sender);
        void __fastcall mnDeleteItemClick(TObject *Sender);
        void __fastcall mnDisplayItemClick(TObject *Sender);
        void __fastcall sgMeasureMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall mnSaveClick(TObject *Sender);
        void __fastcall btnHorLineClick(TObject *Sender);
        void __fastcall btnVerLineClick(TObject *Sender);
        void __fastcall pcInspectionChange(TObject *Sender);
        void __fastcall btnLineColorClick(TObject *Sender);
        void __fastcall btnFontColorClick(TObject *Sender);
        void __fastcall btnTextColorClick(TObject *Sender);
        void __fastcall imInspectionDblClick(TObject *Sender);
        void __fastcall cbAutoExposureClick(TObject *Sender);
        void __fastcall cbMeasureCrossLineClick(TObject *Sender);
        void __fastcall cbMicroCrossLineClick(TObject *Sender);
        void __fastcall cbMacroBackCrossLineClick(TObject *Sender);
        void __fastcall cbMacroTopCrossLineClick(TObject *Sender);
        void __fastcall btnDICNearClick(TObject *Sender);
        void __fastcall btnDICFarClick(TObject *Sender);
        void __fastcall mnDeleteAllClick(TObject *Sender);
        void __fastcall btnHeightClick(TObject *Sender);
        void __fastcall rgMoveStepMeasureClick(TObject *Sender);
        void __fastcall tbDICFCMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall tbDICFCMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
        void __fastcall tbDICFCMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnMoveUpMeasureClick(TObject *Sender);
        void __fastcall btnMoveDownMeasureClick(TObject *Sender);
        void __fastcall btnTOrgClick(TObject *Sender);
        void __fastcall btnAS0Click(TObject *Sender);
        void __fastcall btnToEdgeClick(TObject *Sender);
        void __fastcall cbFreezeClick(TObject *Sender);
        void __fastcall cbFreezeRLClick(TObject *Sender);
        void __fastcall sgDieDblClick(TObject *Sender);
        void __fastcall sgDieMouseMove(TObject *Sender, TShiftState Shift,
          int X, int Y);
        void __fastcall btnBackwardZ1Click(TObject *Sender);
        void __fastcall btnMoveZ1Click(TObject *Sender);
        void __fastcall btnCW1xMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnCW1xMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnCCW1xMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnCCW1xMouseUp(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnFindCenterClick(TObject *Sender);
        void __fastcall btnAlignmentClick(TObject *Sender);
        void __fastcall btnAutoMatchClick(TObject *Sender);
        void __fastcall tmFindCenterTimer(TObject *Sender);
        void __fastcall mnDefectPassClick(TObject *Sender);
        void __fastcall sgBINCodeMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall mnDefectRejectClick(TObject *Sender);
        void __fastcall sgBINCodeResultDrawCell(TObject *Sender, int ACol,
          int ARow, TRect &Rect, TGridDrawState State);
        void __fastcall mnDefectNoneClick(TObject *Sender);
        void __fastcall mnAddPointClick(TObject *Sender);
        void __fastcall mnDeletePointClick(TObject *Sender);
        void __fastcall mnRestorePointClick(TObject *Sender);
        void __fastcall sgDefectListMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall pnlMacroJudageDoneClick(TObject *Sender);
        void __fastcall pnlMicroJudageDoneClick(TObject *Sender);
        void __fastcall btnDrawMapClick(TObject *Sender);
        void __fastcall imPatternClick(TObject *Sender);
        void __fastcall btnSaveDieClick(TObject *Sender);
        void __fastcall mnAddSubDieClick(TObject *Sender);
        void __fastcall sgDieMouseDown(TObject *Sender,
          TMouseButton Button, TShiftState Shift, int X, int Y);
        void __fastcall btnStopSaveClick(TObject *Sender);
        void __fastcall shCurretnPositionMouseMove(TObject *Sender,
          TShiftState Shift, int X, int Y);
private:	// User declarations
public:		// User declarations
        __fastcall TfrmInspection(TComponent* Owner);


   // Wafer Map
   void __fastcall TfrmInspection::DrawBigImage(int mode);
   void __fastcall TfrmInspection::InitWaferMap();
   bool __fastcall TfrmInspection::InMeasure(int row,int col, bool first);
   bool __fastcall TfrmInspection::InSelect(int row,int col);
   bool __fastcall TfrmInspection::InCenterDie1(int row,int col);
   void __fastcall TfrmInspection::DrawRowCol(int sx,int sy,int col,int row,int type, int factor);
   struct WAFER_STRU    {
      int X,Y,Dx,Dy;
      bool boolSet;
      int Width,Height;
      int Cx,Cy;
   };
   struct WAFER_STRU Wafer;
   void __fastcall TfrmInspection::RowColToXY(int *x, int *y);
   int ImageFactor,ImageLeftFactor,ImageRightFactor;
   void __fastcall TfrmInspection::SetMainFun(bool mode);
   void __fastcall TfrmInspection::SetBackFun(bool mode);
   void __fastcall TfrmInspection::SetTopFun(bool mode);
   void __fastcall TfrmInspection::ResetTopOpeation();
   void __fastcall TfrmInspection::SetIntensity(int no);
   int WheelCCD;
   void __fastcall TfrmInspection::UpdateResult();
   #define JUDGE_PASS                           1
   #define JUDGE_REJECT                         2
   #define JUDGE_NONE                           3
   #define JUDGE_NA                             4
   int MicroResult,MacroTopResult,MacroBackResult;
   void __fastcall TfrmInspection::SetupBINCode();
   void __fastcall TfrmInspection::SetupDefectList();

   // CCD FOV vs CCDImage Area
   int CCDRangeX,CCDRangeY,CCDDx,CCDDy;
   int LaserCenterX,LaserCenterY;
   void __fastcall TfrmInspection::DoInverse();
   void __fastcall TfrmInspection::UpdateCurrentPosition();
   void __fastcall TfrmInspection::UpdateMotionPosition();
   void __fastcall TfrmInspection::GetStatus();
   void __fastcall TfrmInspection::AddMeasureMessage(AnsiString msg);
   void __fastcall TfrmInspection::GetFactor(double *fx,double *fy,double x1, double y1, double x2, double y2);
   // Measure
   int MeasureState;
   int Mx1,My1,Mx2,My2;
   void __fastcall TfrmInspection::GridTitle();
   void __fastcall TfrmInspection::AddMeasureData();
   void __fastcall TfrmInspection::DrawToMeasure();
   // 2023 2 12 - chc Serial No: top/Left/Right
   int TopSeialNo;
   int TopLeftSeialNo;
   int TopRightSeialNo;
   int BackLeftSeialNo;
   int BackRightSeialNo;
   void __fastcall TfrmInspection::LoadTXTFile(AnsiString fname);
   void __fastcall TfrmInspection::SetupBINCodeNew();

   // 2023 3 22 - chc Sub-Die
   void __fastcall TfrmInspection::DrawSubDieMap(int sx,int sy,int ex,int ey,int mode);
   void __fastcall TfrmInspection::DrawSubDie();
   void __fastcall TfrmInspection::FindEdge(int no,int *retx,int *rety);
   void __fastcall TfrmInspection::RemoteRotate(int x1,int y1, int x2, int y2);
   bool __fastcall TfrmInspection::DoNCCMatch(int stdwidth,int stdheight, AnsiString patternfname);
   int MarkCenterX,MarkCenterY;
   void __fastcall TfrmInspection::FindCenter(int x1,int y1,int x2,int y2,int x3,int y3,int *rcx,int *rcy);
   double __fastcall TfrmInspection::GetLensPrecision();
   int RotateLeftXPos,RotateRightXPos;
   int RotateLeftYPos,RotateRightYPos;
   // 加入Position的記錄, 否則長距離的轉正與單畫面的轉正方向相反!!
   int RotateLeftXCmd,RotateRightXCmd;
   int RotateLeftYCmd,RotateRightYCmd;
   // 記錄作業時間長度
   long NCCStartTime,NCCStopTime,NCCElapsedms;
   short NCCStartTick,NCCStopTick;
   bool __fastcall TfrmInspection::CheckNCCMatch();
   void __fastcall TfrmInspection::SetupBINCodeTitle();
   void __fastcall TfrmInspection::SetupDefectListTitle();
   void __fastcall TfrmInspection::SaveResultMap(bool bjudge);

   // 2023 4 12 - chc Add Defect
   void __fastcall TfrmInspection::AddPointData();
   bool boolFromSave;

   // 2023 4 14 - chc Switch Lens/Intensity/Observation/DIC
   void __fastcall TfrmInspection::SwitchInspectCondition(int no);

   // 2023 4 28 - chc Capture cnt: CaptureCount
   int CaptureCount;

};
//---------------------------------------------------------------------------
extern PACKAGE TfrmInspection *frmInspection;
//---------------------------------------------------------------------------
#endif
